### ISSUE TITLE
如何在xml中配置按钮？

### ISSUE THREAD

**Issue by hongliGG** [RRRoger/odoo_addons#3]
你好， 我使用的是odoo13， 我在sale.order 的tree视图上直接添加<tree buttons='[]'/>属性，会报无效的视图错误。我想请教一下，这个我应该怎么配置

**Comment by RRRoger** [comment]
你好, 目前这个addon仅支持odoo9,10, 还不支持13, 需要再研究一下

**Comment by RRRoger** [comment]
不在支持odoo12以上
