### ISSUE TITLE
odoo14安装报错

### ISSUE THREAD

**Issue by 516300502** [RRRoger/odoo_addons#4]
odoo14安装后出现以下截图错误
![image](https://user-images.githubusercontent.com/37934050/128658103-1279d6d7-d591-4d2c-b252-945e77805299.png)

**Comment by RRRoger** [comment]
sorry, 这个版本目前只支持odoo10，新版本对各个视图的xml做了规则限制，需要再研究研究

**Comment by RRRoger** [comment]
> sorry, 这个版本目前只支持odoo10，新版本对各个视图的xml做了规则限制，需要再研究研究

@516300502

**Comment by 516300502** [comment]
> > sorry, 这个版本目前只支持odoo10，新版本对各个视图的xml做了规则限制，需要再研究研究
> 
> @516300502
好的，我也再看下
